vich_uploader:
    db_driver: orm

    mappings:
        avatar:
            uri_prefix: 'assets/images/avatar'
            upload_destination: '%kernel.project_dir%/assets/images/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # or any other namer listed above

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true